version: '3.8'

services:
  skillmap-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      # Add your environment variables here
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - QDRANT_URL=${QDRANT_URL}
      # - QDRANT_API_KEY=${QDRANT_API_KEY}
    volumes:
      # Mount uploads directory for file storage
      - ./uploads:/usr/src/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - skillmap-network

  # Optional: Add Qdrant if you want to run it locally
  # qdrant:
  #   image: qdrant/qdrant:latest
  #   ports:
  #     - "6333:6333"
  #   volumes:
  #     - qdrant_storage:/qdrant/storage
  #   networks:
  #     - skillmap-network

networks:
  skillmap-network:
    driver: bridge

# volumes:
#   qdrant_storage:
